/* Debugging */
#define BUFFERINITDEBUG 0
#define BUFFERREQUESTDEBUG 0
#define BUFFERINPUTDEBUG 0
#define PACKETREADDEBUG 0
#define PACKETWRITEDEBUG 0
#define TRANSPORTDQDEBUG 0
#define TRANSPORTPORTQDEBUG 1
